repl:
	/Applications/factor/Factor.app/Contents/MacOS/factor

init:
	brew cask install factor

hello-world:
	export FACTOR_ROOTS=$(CURDIR)
	/Applications/factor/Factor.app/Contents/MacOS/factor examples/hello/hello.factor

greeter-tests:
	export FACTOR_ROOTS=$(CURDIR)
	/Applications/factor/Factor.app/Contents/MacOS/factor examples/greeter/greeter-tests.factor

strings-tests:
	export FACTOR_ROOTS=$(CURDIR)
	/Applications/factor/Factor.app/Contents/MacOS/factor examples/strings/strings-tests.factor

sequences-tests:
	export FACTOR_ROOTS=$(CURDIR)
	/Applications/factor/Factor.app/Contents/MacOS/factor examples/sequences/sequences-tests.factor

tuples-tests:
	export FACTOR_ROOTS=$(CURDIR)
	/Applications/factor/Factor.app/Contents/MacOS/factor examples/tuples/tuples-tests.factor


checkout-tests:
	export FACTOR_ROOTS=$(CURDIR)
	/Applications/factor/Factor.app/Contents/MacOS/factor examples/checkout/checkout-tests.factor


fizzbuzz:
	export FACTOR_ROOTS=$(CURDIR)
	/Applications/factor/Factor.app/Contents/MacOS/factor examples/fizzbuzz/fizzbuzz.factor
