repl:
	elm repl


init:
	brew install elm

setup:
	elm install elm/http
	elm install elm/json
	elm install mdgriffith/elm-ui
	elm install mpizenberg/elm-pointer-events

main:
	elm make src/Main.elm

homepage:
	elm make src/HomePage.elm --output elm.js
