using Pkg
Pkg.add("DataFrames")
Pkg.add("PyCall")
Pkg.add("RCall")
Pkg.add("RDatasets")
Pkg.add("CSV")
Pkg.add("DataFramesMeta")
Pkg.add("Dates")
Pkg.add("Feather")
Pkg.add("Gadfly")
Pkg.add("DataTables")
Pkg.add("RollingFunctions")
Pkg.add("Printf")
Pkg.build("RCall")
Pkg.add("IJulia")
Pkg.add("Query")
